apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  type: ClusterIP
  # 仮想IPを静的に設定する
  # ただし一度applyした後に変更することはできない
  clusterIP: 10.11.253.81
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: sample-app