apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - image: nginx:1.12
      name: nginx-container
      volumeMounts:
        - mountPath: /srv
          name: hostpath-sample
          # ReadOnlyにする
          readOnly: true
  volumes:
    - name: hostpath-sample
      hostPath:
        path: /etc
        type: DirectoryOrCreate