apiVersion: v1
kind: Service
metadata:
  name: {{ template "echo.fullname" . }}
  labels:
    app: {{ template "echo.name" . }}
    chart: {{ template "echo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ template "echo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
