apiVersion: v1
kind: Pod
metadata:
  name: sample-2-pod
spec:
  containers:
    # Pod内のコンテナはNICを共有している
    # そのため、以下の例では両方ともTCPのポート80を使用するのでエラーになる
    - name: nginx-container-112
      image: nginx:1.12
    - name: nginx-container-113
      image: nginx:1.13