apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - name: secret-image-container
      image: REGISTRY_NAME/secret-image:latest
  # イメージ取得時のSecretの利用
  imagePullSecrets:
    - name: sample-secret