apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-pv
  # ラベル
  labels:
    type: gce-pv
    environment: stg
spec:
  # 容量
  capacity:
    storage: 10Gi
  # アクセスモード
  accessModes:
    - ReadWriteOnce
  # Reclaim Policy
  persistentVolumeReclaimPolicy: Retain
  # StorageClass
  storageClassName: manual
  # PersistentVolumeプラグインごとの設定
  gcePersistentDisk:
    pdName: sample-gce-pv
    fsType: ext4