apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-limitrange
  namespace: default
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: 10gi
      min:
        storage: 3Gi