apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - name: configmap-container
      image: nginx:1.12
      envFrom:
        - configMapRef:
            name: sample-configmap