apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-container
  namespace: default
spec:
  hard:
    # 作成可能なリソースの数(新記法)
    count/persistentvolumeclaims: 10
    count/services: 10
    count/secrets: 10
    count/configmaps: 10
    count/replicationcontrollers: 10
    count/deployments.apps: 10
    count/replicasets.apps: 10
    count/statefulsets.apps: 10
    count/jobs.batch: 10
    count/cronjobs.batch: 10
    count/deployments.extensions: 10

    # 作成可能なリソースの数(旧記法)
    # 旧記法ではtypeごとのリソース制限も可能
    sample-storageclass.storageclass.storage.k8s.io/persistentvolumeclaims: 10
    services.loadbalancers: 10
    services.nodeports: 10
    pod: 10
    persistentvolumeclaims: 10
    replicationcontrollers: 10
    secrets: 10
    configmaps: 10
    services: 10
    resourcequotas: 10

    # リソース使用量の制限
    requests.cpu: 2
    requests.memory: 2Gi
    requests.storage: 5Gi
    sample-storageclass.storageclass.storage.k8s.io/requests.storage: 5Gi
    requests.ephemeral-storage: 5Gi
    requests.nvidia.com/gpu: 2

    limits.cpu: 4
    limits.memory: 4Gi
    limits.ephemeral-storage: 10Gi
    limits.nvidia.com/gpu: 4